### ISSUE TITLE
Publish to maven central

### ISSUE THREAD

**Issue by koppor** [bkromhout/java-diff-utils#2]
This fork seems to be the most actively maintained, therefore I propose to publish this work on MavenCentral. For that, the GroupId has to be adapted.

Currently, the groupId is `com.github.java-diff-utils`:  (https://github.com/bkromhout/java-diff-utils/blob/master/build.gradle#L4) I think, this should be changed to `com.github.bkromhout`.

Minor comment: The Changelog states a change in the groupId (commit: https://github.com/bkromhout/java-diff-utils/commit/42d93b3e5bf418c4f724b7afe5b1939aea6aa663):

> hange groupId and artifactId to prevent conflict with origin library: now 'com.github.java-diff-utils:java-diff-utils' instead of 'jp.skypencil.java-diff-utils:diffutils'

This change was introduced at https://github.com/jycr/java-diff-utils and does not affect this repository. `jp.skypencil.java-diff-utils` is also available on MavenCentral: http://search.maven.org/#search%7Cga%7C1%7Cjava-diff-utils - I would, however, not go back to com.googlecode as this has no relation with this repository here (`bkromhout`).

After the change of the groupId, this fork can be published to MavenCentral.

The modern gradle way seems to be https://docs.gradle.org/current/userguide/publishing_maven.html. One can also just generate the POM required for publishing: https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:generate-pom

**Comment by bkromhout** [comment]
Hi Oliver, thanks for your interest in this. I was actually thinking about doing this just the other day.

As you mention, I will have to change the package name since Maven Central has extremely strict guidelines about having to have control over the domain your groupId is a reverse of.

Following that, I'll likely publish to JFrog's jCenter first, and then sync to Maven Central from there. Reason being that many projects (especially Android projects, which is my common purview) use jCenter these days rather than Maven Central.

Hopefully I'll be able to get this all done soon, but with the holidays it might take a bit (especially since all Maven Central additions are manually reviewed, if their process hasn't changed since I last tried).

Thanks!

**Comment by koppor** [comment]
jcenter is fine for me 😇  -> I'm also using jcenter -> https://github.com/JabRef/jabref/blob/master/build.gradle#L51

**Comment by bkromhout** [comment]
Excellent, that makes it much simpler!

**Comment by bkromhout** [comment]
Hi @koppor, as you can see [here on Bintray](https://bintray.com/bkromhout/maven/java-diff-utils), I have uploaded java-diff-utils and have managed to get it linked into jCenter. 

You should now be able to resolve the dependency by adding this line to your `build.gradle` file:
```groovy
compile 'com.github.bkromhout:java-diff-utils:2.1.1'
```

Once you verify that it works for you, I'll add that to the README so everyone can benefit.

**Comment by koppor** [comment]
```
Download https://jcenter.bintray.com/com/github/bkromhout/java-diff-utils/2.1.1/java-diff-utils-2.1.1.pom
Download https://jcenter.bintray.com/com/github/bkromhout/java-diff-utils/2.1.1/java-diff-utils-2.1.1.jar
```

The JAR is only 1kb in size and only contains an empty MANIFEST.MF

**Comment by bkromhout** [comment]
Ha, well that certainly isn't right! Let me take a look, I clearly must have missed something 😅

**Comment by bkromhout** [comment]
@koppor Yep, bit of a snafu with the project structure. It should be correct this time around, I've verified the JAR actually contains the classes this time. Sorry about that!

**Comment by koppor** [comment]
This time, I can confirm that it works fine: https://travis-ci.org/JabRef/jabref/builds/178358084 Thank you for the quick action!

**Comment by koppor** [comment]
Could you continue trying to publish to maven central? 😇 [VersionEye](http://versioneye.com/) does not crawl repos offered by jFrog and cannot change this behavior (non-technical reasons).
